### ISSUE TITLE
Posts and Author are reversed

### ISSUE THREAD

**Issue by wootwoot1234** [Makepad-fr/facebook-group-posts-scraper#16]
Posts and Author are incorrect.  It's saving the Author as the post and the post as the author.  :)

https://github.com/Makepad-fr/facebook-group-posts-scraper/blob/1be651f820eec55a7c8598ee87363aab82f79411/src/index.js#L489-L490

**Comment by kaanyagci** [comment]
Hi @wootwoot1234,

As you can see on the lines above this statement (between lines 475-485), the initialization made as the first element of the array has the post content. The second element of the array has the author element. I assume that this implementation is not really clear, but it is not problematic at the end of the execution.
